const teams = [
    {
        teamName: 'Med Fc',
        teamId: 'Medox24',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Pala',
        teamId: 'Ilyass',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Zooooooooooot',
        teamId: 'Pop',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Thorny Dragon',
        teamId: 'Adam',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'البوال',
        teamId: 'NO9TA',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'الخراي',
        teamId: 'Abdo tiger',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Zelala',
        teamId: 'Wassim the real',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Milan',
        teamId: 'Habiboff',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'ro3b☠️',
        teamId: 'to9os ifri9ya',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'صلي على محمد',
        teamId: 'سفيان',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'maroc',
        teamId: 'adriano',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Japane',
        teamId: 'ABDO',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'F PES ANA SULTAN',
        teamId: 'KAIDO_MORRI',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Thelegend',
        teamId: 'Thelegend',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'L9irch',
        teamId: 'Moncef',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: '5yearsjail',
        teamId: '5yearsjail',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'العذاب اخويا العذاب',
        teamId: 'Mehdi-rhou',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'FC BARCELONA',
        teamId: 'MESSSI',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Johny sins',
        teamId: 'Ast3ax',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Chill guy',
        teamId: 'Reda',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'FAR BEFORE ABC',
        teamId: 'Abdessamad',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Chrwit',
        teamId: 'Amine',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'نادي الجيش الملكي',
        teamId: 'Zakaria',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Saudi the second',
        teamId: 'Yahya05',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'SIMO',
        teamId: 'MOHAMED',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },

    {
        teamName: 'Dos Kallas',
        teamId: 'Aymane',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },

    {
        teamName: 'Lmasoniya',
        teamId: 'AMINE',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'Olympique de Safi',
        teamId: 'Younes marouri',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'FARI9 LMXRML',
        teamId: 'Hamada',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
    {
        teamName: 'CR Flamengo',
        teamId: 'M_4<',
        GF: 0,
        GA: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        KOGF : 0 ,
        KOGA : 0
    },
];

export default teams;